### ISSUE TITLE
Reading data from Pandas

### ISSUE THREAD

**Issue by venkatsanka** [justmarkham/pycon-2016-tutorial#1]
Hi Kevin, 
i am trying to read the sms dataset , through which when i check the shape i am getting a different number rather than the number of rows .. 

url = 'https://github.com/justmarkham/pycon-2016-tutorial/blob/master/data/sms.tsv'
sms = pd.read_table(url,header=None,names=['label','message'])

sms.shape
(22801, 2)

also its throwing some html values in label and NaN in message series . when i check 
sms.head(10)
	label	message
0	<!DOCTYPE html>	NaN
1	<html lang="en">	NaN
2	<head>	NaN
3	<meta charset="utf-8">	NaN
4	<link rel="dns-prefetch" href="https://asset...	NaN
5	<link rel="dns-prefetch" href="https://avata...	NaN
6	<link rel="dns-prefetch" href="https://avata...	NaN
7	<link rel="dns-prefetch" href="https://avata...	NaN
8	<link rel="dns-prefetch" href="https://avata...	NaN
9	<link rel="dns-prefetch" href="https://githu...	NaN

not sure what i am doing wrong here ... could you suggest please ?

**Comment by justmarkham** [comment]
The URL you are accessing is an HTML webpage, even though the URL ends with 'tsv'. Instead, you need to click the "raw" button on that webpage, which gives you this URL:

https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv

Pandas can read from that URL. Hope that helps!

**Comment by venkatsanka** [comment]
My bad... anyways thank you so much for the response !!!!
